

[main]
#font=Latin Modern Mono:size=14
font=Courier New:size=14
bold-text-in-bright=yes

[environment]
SHLVL=0

[bell]
system=no
visual=yes

[scrollback]
lines=5000
#indicator-format=line

[cursor]
blink-rate=750
color=000000 aaffaa

[colors]
background=070707
foreground=ffffff
regular0=000000
regular1=ff0000
regular2=00ff00
regular3=ffff00
regular4=0000ff
regular5=ff00ff
regular6=00ffff
regular7=ffffff
flash=7f7f7f

[tweak]
bold-text-in-bright-amount=1.2